/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import estructurasDatos.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import pruebas.ArbolAVL;
import pruebas.NodoAVL;



/**
 *
 * @author Cristhian
 */
public class Login extends javax.swing.JFrame {
    Persona usuario;
   ArbolAVL<Persona> usuarios;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.usuario=null;
        this.usuarios=null;
        jLabelError.setVisible(false);
    }
    
    public Login(ArbolAVL usuarios) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.usuario=null;
        this.usuarios=usuarios;
        jLabelError.setVisible(false);
    }

    public Persona getUsuario() {
        return usuario;
    }

    public void setUsuario(Estudiante usuario) {
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoLogin = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTituloApp = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoLogin.setBackground(new java.awt.Color(255, 255, 255));
        FondoLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        FondoLogin.setPreferredSize(new java.awt.Dimension(1050, 580));

        jLabelNombreUsuario.setBackground(new java.awt.Color(102, 0, 102));
        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNombreUsuario.setText("Nombre de Usuario");

        jLabelContraseña.setBackground(new java.awt.Color(102, 0, 102));
        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContraseña.setText("Contraseña");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/telescope_icon_125404.png"))); // NOI18N

        jLabelTituloApp.setFont(new java.awt.Font("Pristina", 0, 48)); // NOI18N
        jLabelTituloApp.setForeground(new java.awt.Color(102, 0, 102));
        jLabelTituloApp.setText("FORSCHER");

        jTextNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreUsuarioActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jButtonIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonIniciarSesion.setText("Iniciar Sesión");
        jButtonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIniciarSesionMouseClicked(evt);
            }
        });
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jLabelRegistro.setText("¿No tienes cuenta en Forscher? ");

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(0, 204, 204));
        jButtonRegistrar.setText("Regístrate");
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout FondoLoginLayout = new javax.swing.GroupLayout(FondoLogin);
        FondoLogin.setLayout(FondoLoginLayout);
        FondoLoginLayout.setHorizontalGroup(
            FondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLoginLayout.createSequentialGroup()
                .addGroup(FondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTituloApp, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(jButtonIniciarSesion))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabelRegistro)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonRegistrar))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        FondoLoginLayout.setVerticalGroup(
            FondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(FondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloApp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonIniciarSesion)
                .addGap(22, 22, 22)
                .addComponent(jLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLoginLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelRegistro))
                    .addComponent(jButtonRegistrar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreUsuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
    Register registro = new Register(usuarios);
    registro.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionMouseClicked
        // TODO add your handling code here:
        if(this.usuarios==null){
            jLabelError.setVisible(true);
            jLabelError.setText("Todavía no hay cuentas registradas, sé el primero");
        }else{
        NodoAVL<Persona> user=null;
        long inicio=System.nanoTime();
        user = this.usuarios.buscar(jTextNombreUsuario.getText(), this.usuarios.raiz);
        long finall=System.nanoTime();
        double dif= (double)(finall-inicio)*1.0e-6;
        System.out.println(dif);
        if(user!=null){
            this.usuario=user.dato;
        }else{
          jLabelError.setVisible(true);
            jLabelError.setText("El usuario digitado no existe");
        }
           // System.out.println(usuario.getContrasena());
        if(this.usuario != null&&this.usuario.getContrasena().equals(jPassword.getText())){
        MenuPrincipal menu = new MenuPrincipal(this.usuario,this.usuarios);
        menu.setVisible(true);
        dispose();
        }else{
            jLabelError.setVisible(true);
            jLabelError.setText("Error en el usuario o la contraseña");
        }
         
        }
    }//GEN-LAST:event_jButtonIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        BufferedReader bf=null;
                try {
                   ArbolAVL<Persona> usuarios = new ArbolAVL();
                    bf = new BufferedReader(new FileReader("Diez.txt"));
                    String sCadena;
                    long inicio=System.nanoTime();
                    while ((sCadena = bf.readLine())!=null) {
                        int cont2 = 0;
                        String[] tempo = new String[9];
                        StringTokenizer st = new StringTokenizer(sCadena,";");
                        while (st.hasMoreTokens()){
                            tempo[cont2] = st.nextToken("\t");
                             //System.out.println(tempo[cont2]+"------------------------"+cont2);
                            cont2++;
                        }    
                        //nombre_usuario	genero	nombre	apellido	universidad	carrera	contraseña
                        //System.out.println(tempo[0]+tempo[1]+tempo[2]+ tempo[3]+tempo[4]+tempo[5]+ tempo[6]);
                        Persona estudiante = new Estudiante(tempo[0],tempo[1], tempo[2], tempo[3],tempo[4], tempo[5], tempo[6],"CS");
                        usuarios.insertarNormal(estudiante, estudiante.idUsuario);
                        //System.out.println(estudiante.toString());
                    }
                    
                    long finall=System.nanoTime();
                    double dif= (double)(finall-inicio)*1.0e-6;
                    System.out.println(dif);  
                    new Login(usuarios).setVisible(true);
                    
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        bf.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoLogin;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelTituloApp;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
