/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import estructurasDatos.Persona;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;
import pruebas.ArbolAVL;
import pruebas.NodoAVL;

/**
 *
 * @author Cristhian
 */
public class MenuPrincipal extends javax.swing.JFrame {
     private Persona usuario;
     ArbolAVL usuarios;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Persona usuario,ArbolAVL usuarios) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.usuario = usuario;
        this.usuarios = usuarios;
        jButtonFotoPerfil.setIcon(usuario.getImagen());
        jLabelNombre.setText(usuario.getNombre());
        jLabelUsuario.setText(usuario.getClass().getSimpleName());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoMenu = new javax.swing.JPanel();
        SuperiorApp = new javax.swing.JPanel();
        jButtonConfig = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PropiedadesApp = new javax.swing.JPanel();
        jLabelOptions = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelButtonMatch = new javax.swing.JPanel();
        jButtonMatch = new javax.swing.JButton();
        jPanelButtonNotificacion = new javax.swing.JPanel();
        jButtonNotificacion = new javax.swing.JButton();
        jPanelButtonChat = new javax.swing.JPanel();
        jButtonChat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelButtonCerrarS = new javax.swing.JPanel();
        jButtonCerrarS = new javax.swing.JButton();
        jLabelMas = new javax.swing.JLabel();
        jButtonFotoPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoMenu.setBackground(new java.awt.Color(255, 255, 255));
        FondoMenu.setPreferredSize(new java.awt.Dimension(1050, 580));

        SuperiorApp.setBackground(new java.awt.Color(102, 0, 102));

        jButtonConfig.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConfig.setForeground(new java.awt.Color(255, 153, 153));
        jButtonConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/configrotate.png"))); // NOI18N
        jButtonConfig.setBorder(null);
        jButtonConfig.setBorderPainted(false);
        jButtonConfig.setContentAreaFilled(false);
        jButtonConfig.setDefaultCapable(false);
        jButtonConfig.setFocusPainted(false);
        jButtonConfig.setFocusable(false);
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });

        jTextBuscar.setBackground(new java.awt.Color(100, 0, 100));
        jTextBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTextBuscar.setText("Buscar...");
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORSCHER");

        javax.swing.GroupLayout SuperiorAppLayout = new javax.swing.GroupLayout(SuperiorApp);
        SuperiorApp.setLayout(SuperiorAppLayout);
        SuperiorAppLayout.setHorizontalGroup(
            SuperiorAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorAppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuperiorAppLayout.setVerticalGroup(
            SuperiorAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorAppLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(SuperiorAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SuperiorAppLayout.createSequentialGroup()
                .addGroup(SuperiorAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addGroup(SuperiorAppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelOptions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOptions.setForeground(new java.awt.Color(153, 153, 153));
        jLabelOptions.setText("OPCIONES");

        jLabelNombre.setForeground(new java.awt.Color(102, 102, 102));

        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));

        jButtonMatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sugerir.png"))); // NOI18N
        jButtonMatch.setText("¡HAZ MATCH!");
        jButtonMatch.setBorder(null);
        jButtonMatch.setBorderPainted(false);
        jButtonMatch.setContentAreaFilled(false);
        jButtonMatch.setDefaultCapable(false);
        jButtonMatch.setFocusPainted(false);
        jButtonMatch.setHideActionText(true);
        jButtonMatch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonMatch.setIconTextGap(25);
        jButtonMatch.setRequestFocusEnabled(false);
        jButtonMatch.setRolloverEnabled(false);
        jButtonMatch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sugerir.png"))); // NOI18N
        jButtonMatch.setVerifyInputWhenFocusTarget(false);
        jButtonMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMatchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMatchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMatchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonMatchLayout = new javax.swing.GroupLayout(jPanelButtonMatch);
        jPanelButtonMatch.setLayout(jPanelButtonMatchLayout);
        jPanelButtonMatchLayout.setHorizontalGroup(
            jPanelButtonMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelButtonMatchLayout.setVerticalGroup(
            jPanelButtonMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonMatchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonNotificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nonotificacion.png"))); // NOI18N
        jButtonNotificacion.setText("Notificaciones");
        jButtonNotificacion.setBorder(null);
        jButtonNotificacion.setBorderPainted(false);
        jButtonNotificacion.setContentAreaFilled(false);
        jButtonNotificacion.setDefaultCapable(false);
        jButtonNotificacion.setFocusPainted(false);
        jButtonNotificacion.setHideActionText(true);
        jButtonNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNotificacion.setIconTextGap(25);
        jButtonNotificacion.setRequestFocusEnabled(false);
        jButtonNotificacion.setRolloverEnabled(false);
        jButtonNotificacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sugerir.png"))); // NOI18N
        jButtonNotificacion.setVerifyInputWhenFocusTarget(false);
        jButtonNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNotificacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNotificacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNotificacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonNotificacionLayout = new javax.swing.GroupLayout(jPanelButtonNotificacion);
        jPanelButtonNotificacion.setLayout(jPanelButtonNotificacionLayout);
        jPanelButtonNotificacionLayout.setHorizontalGroup(
            jPanelButtonNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelButtonNotificacionLayout.setVerticalGroup(
            jPanelButtonNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonNotificacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonChat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sinchat.png"))); // NOI18N
        jButtonChat.setText("Chats");
        jButtonChat.setBorder(null);
        jButtonChat.setBorderPainted(false);
        jButtonChat.setContentAreaFilled(false);
        jButtonChat.setDefaultCapable(false);
        jButtonChat.setFocusPainted(false);
        jButtonChat.setHideActionText(true);
        jButtonChat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonChat.setIconTextGap(25);
        jButtonChat.setRequestFocusEnabled(false);
        jButtonChat.setRolloverEnabled(false);
        jButtonChat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sugerir.png"))); // NOI18N
        jButtonChat.setVerifyInputWhenFocusTarget(false);
        jButtonChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonChatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonChatLayout = new javax.swing.GroupLayout(jPanelButtonChat);
        jPanelButtonChat.setLayout(jPanelButtonChatLayout);
        jPanelButtonChatLayout.setHorizontalGroup(
            jPanelButtonChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelButtonChatLayout.setVerticalGroup(
            jPanelButtonChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonChatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonChat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonCerrarS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cerrarsesion.png"))); // NOI18N
        jButtonCerrarS.setText("Cerrar Sesion");
        jButtonCerrarS.setBorder(null);
        jButtonCerrarS.setBorderPainted(false);
        jButtonCerrarS.setContentAreaFilled(false);
        jButtonCerrarS.setDefaultCapable(false);
        jButtonCerrarS.setFocusPainted(false);
        jButtonCerrarS.setHideActionText(true);
        jButtonCerrarS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCerrarS.setIconTextGap(25);
        jButtonCerrarS.setRequestFocusEnabled(false);
        jButtonCerrarS.setRolloverEnabled(false);
        jButtonCerrarS.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sugerir.png"))); // NOI18N
        jButtonCerrarS.setVerifyInputWhenFocusTarget(false);
        jButtonCerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCerrarSMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonCerrarSLayout = new javax.swing.GroupLayout(jPanelButtonCerrarS);
        jPanelButtonCerrarS.setLayout(jPanelButtonCerrarSLayout);
        jPanelButtonCerrarSLayout.setHorizontalGroup(
            jPanelButtonCerrarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCerrarS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelButtonCerrarSLayout.setVerticalGroup(
            jPanelButtonCerrarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonCerrarSLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCerrarS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelMas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMas.setForeground(new java.awt.Color(153, 153, 153));
        jLabelMas.setText("MÁS");

        jButtonFotoPerfil.setBorderPainted(false);
        jButtonFotoPerfil.setContentAreaFilled(false);
        jButtonFotoPerfil.setDefaultCapable(false);
        jButtonFotoPerfil.setFocusPainted(false);
        jButtonFotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PropiedadesAppLayout = new javax.swing.GroupLayout(PropiedadesApp);
        PropiedadesApp.setLayout(PropiedadesAppLayout);
        PropiedadesAppLayout.setHorizontalGroup(
            PropiedadesAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jPanelButtonMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButtonNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButtonChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jPanelButtonCerrarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PropiedadesAppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PropiedadesAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropiedadesAppLayout.createSequentialGroup()
                        .addComponent(jButtonFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(PropiedadesAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelOptions)
                    .addComponent(jLabelMas))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PropiedadesAppLayout.setVerticalGroup(
            PropiedadesAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropiedadesAppLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PropiedadesAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropiedadesAppLayout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsuario))
                    .addComponent(jButtonFotoPerfil))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtonMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtonNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtonChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanelButtonCerrarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FondoMenuLayout = new javax.swing.GroupLayout(FondoMenu);
        FondoMenu.setLayout(FondoMenuLayout);
        FondoMenuLayout.setHorizontalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(SuperiorApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PropiedadesApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(866, 866, 866))
        );
        FondoMenuLayout.setVerticalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addComponent(SuperiorApp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PropiedadesApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMatchMouseClicked
         // TODO add your handling code here:
         jPanelButtonMatch.setBackground(new java.awt.Color(0, 0, 0));
         jPanelVentantaApp = new PanelMatch();
         jPanelVentantaApp.setLocation(850, 513);
         jPanelVentantaApp.setVisible(true);
       
    }//GEN-LAST:event_jButtonMatchMouseClicked

    private void jButtonMatchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMatchMouseEntered
        // TODO add your handling code here:
        jPanelButtonMatch.setBackground(new java.awt.Color(102, 0, 102));
    }//GEN-LAST:event_jButtonMatchMouseEntered

    private void jButtonMatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMatchMouseExited
        // TODO add your handling code here:
        jPanelButtonMatch.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jButtonMatchMouseExited

    private void jButtonNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNotificacionMouseClicked
        // TODO add your handling code here:
        jPanelButtonNotificacion.setBackground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButtonNotificacionMouseClicked

    private void jButtonNotificacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNotificacionMouseEntered
        // TODO add your handling code here:
        jPanelButtonNotificacion.setBackground(new java.awt.Color(102, 0, 102));
    }//GEN-LAST:event_jButtonNotificacionMouseEntered

    private void jButtonNotificacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNotificacionMouseExited
        // TODO add your handling code here:
        jPanelButtonNotificacion.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jButtonNotificacionMouseExited

    private void jButtonChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChatMouseClicked
        // TODO add your handling code here:
        jPanelButtonChat.setBackground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButtonChatMouseClicked

    private void jButtonChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChatMouseEntered
        // TODO add your handling code here:
        jPanelButtonChat.setBackground(new java.awt.Color(102, 0, 102));
    }//GEN-LAST:event_jButtonChatMouseEntered

    private void jButtonChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChatMouseExited
        // TODO add your handling code here:
        jPanelButtonChat.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jButtonChatMouseExited

    private void jButtonCerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSMouseClicked
        // TODO add your handling code here:
        String opciones[]={"SI","NO"};
        jPanelButtonCerrarS.setBackground(new java.awt.Color(0, 0, 0));
        int eleccion=JOptionPane.showOptionDialog(this,"¿Desea cerrar sesión?", "Título", 0, 0, null, opciones, this);
        if(eleccion==JOptionPane.YES_OPTION){
         Login volver = new Login(usuarios);
          volver.setVisible(true);
          dispose();
        }
        
    }//GEN-LAST:event_jButtonCerrarSMouseClicked

    private void jButtonCerrarSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSMouseEntered
        // TODO add your handling code here:
        jPanelButtonCerrarS.setBackground(new java.awt.Color(102, 0, 102));
    }//GEN-LAST:event_jButtonCerrarSMouseEntered

    private void jButtonCerrarSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSMouseExited
        // TODO add your handling code here:
        jPanelButtonCerrarS.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jButtonCerrarSMouseExited

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        // TODO add your handling code here:
        int posicionPan = this.PropiedadesApp.getX();
        if(posicionPan>=0){
            Animacion.Animacion.mover_izquierda(0,-200, 2, 2, PropiedadesApp);
            jButtonConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config.png")));
            jPanelVentantaApp.setBounds(5, 55, 1040, 513);
        }else{
            Animacion.Animacion.mover_derecha(-200,0, 2, 2, PropiedadesApp);
            jButtonConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/configrotate.png")));
            jPanelVentantaApp.setBounds(195, 55, 850, 513);
        }
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFotoPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(new Login().usuario,new Login().usuarios).setVisible(true);
            }
        });
    }
    private javax.swing.JPanel jPanelVentantaApp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoMenu;
    private javax.swing.JPanel PropiedadesApp;
    private javax.swing.JPanel SuperiorApp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCerrarS;
    private javax.swing.JButton jButtonChat;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonFotoPerfil;
    private javax.swing.JButton jButtonMatch;
    private javax.swing.JButton jButtonNotificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMas;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOptions;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelButtonCerrarS;
    private javax.swing.JPanel jPanelButtonChat;
    private javax.swing.JPanel jPanelButtonMatch;
    private javax.swing.JPanel jPanelButtonNotificacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
}
