/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import estructurasDatos.*;
import java.awt.event.ActionEvent;
import static java.lang.Compiler.command;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import pruebas.ArbolAVL;
import pruebas.NodoAVL;

/**
 *
 * @author Cristhian
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    ArbolAVL usuarios;
    public Register() {
        initComponents();
        this.usuarios=null;
        c_educativo.setEnabled(false);
            programa.setEnabled(false);
            materia.setEnabled(false);
            facultad.setEnabled(false);
        this.setLocationRelativeTo(this);
    }
    
    public Register(ArbolAVL usuarios) {
        initComponents();
        this.usuarios=usuarios;
        c_educativo.setEnabled(false);
            programa.setEnabled(false);
            materia.setEnabled(false);
            facultad.setEnabled(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane = new javax.swing.JScrollPane();
        jPanelFondoRegistro = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonAtras = new javax.swing.JButton();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelAnuncio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDescrpicion = new javax.swing.JTextPane();
        jLabelRol = new javax.swing.JLabel();
        Rol = new javax.swing.JComboBox<>();
        jTextFieldC_Educativo = new javax.swing.JTextField();
        c_educativo = new javax.swing.JComboBox<>();
        jTextFieldPrograma = new javax.swing.JTextField();
        programa = new javax.swing.JComboBox<>();
        jTextFieldMateria = new javax.swing.JTextField();
        jTextFieldFacultad = new javax.swing.JTextField();
        materia = new javax.swing.JComboBox<>();
        facultad = new javax.swing.JComboBox<>();
        jLabelGenero = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jLabelError = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1050, 580));

        jScrollPane.setPreferredSize(new java.awt.Dimension(1050, 580));

        jPanelFondoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jPanelFondoRegistro.setPreferredSize(new java.awt.Dimension(1050, 680));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/telescope_icon_125404.png"))); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Pristina", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 0, 153));
        jLabelTitulo.setText("FORSCHER");

        jLabelNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNombres.setText("Nombres");

        jTextNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombresActionPerformed(evt);
            }
        });

        jLabelApellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelApellidos.setText("Apellidos");

        jTextApellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidosActionPerformed(evt);
            }
        });

        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNombreUsuario.setText("Nombre de Usuario");

        jTextNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreUsuarioActionPerformed(evt);
            }
        });

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContraseña.setText("Contraseña");

        jButtonAtras.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/atras.png"))); // NOI18N
        jButtonAtras.setToolTipText("");
        jButtonAtras.setBorder(null);
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setContentAreaFilled(false);
        jButtonAtras.setDefaultCapable(false);
        jButtonAtras.setFocusPainted(false);
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDescripcion.setText("Descripción:");

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabelAnuncio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAnuncio.setText("Crea tu cuenta en Forscher");

        jTextPaneDescrpicion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneDescrpicion);

        jLabelRol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRol.setText("Rol");

        Rol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor" }));
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });

        jTextFieldC_Educativo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldC_Educativo.setText("Centro Educativo");
        jTextFieldC_Educativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldC_EducativoActionPerformed(evt);
            }
        });

        c_educativo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        c_educativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldPrograma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPrograma.setText("Programa");

        programa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        programa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldMateria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMateria.setText("Materia");
        jTextFieldMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMateriaActionPerformed(evt);
            }
        });

        jTextFieldFacultad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFacultad.setText("Facultad");

        materia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        facultad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        facultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGenero.setText("Género");

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanelFondoRegistroLayout = new javax.swing.GroupLayout(jPanelFondoRegistro);
        jPanelFondoRegistro.setLayout(jPanelFondoRegistroLayout);
        jPanelFondoRegistroLayout.setHorizontalGroup(
            jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                .addComponent(jLabelDescripcion)
                                .addGap(574, 574, 574)
                                .addComponent(jButtonRegistrar))
                            .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                .addComponent(jLabelAnuncio)
                                .addGap(137, 137, 137)
                                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNombres)
                                            .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNombreUsuario)
                                            .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelApellidos)
                                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelRol)
                                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelContraseña)
                                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldC_Educativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_educativo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(83, 83, 83)
                                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(programa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelGenero)
                                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                        .addComponent(jButtonAtras)
                        .addGap(206, 206, 206)
                        .addComponent(jLabelLogo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanelFondoRegistroLayout.setVerticalGroup(
            jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoRegistroLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLogo)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonAtras))
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnuncio)
                    .addComponent(jLabelError))
                .addGap(38, 38, 38)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombres)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero))
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelApellidos)
                        .addComponent(jLabelContraseña)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jTextFieldC_Educativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c_educativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jScrollPane.setViewportView(jPanelFondoRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombresActionPerformed

    private void jTextApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidosActionPerformed

    private void jTextNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreUsuarioActionPerformed

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        Login volver = new Login(usuarios);
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed
        if(Rol.getSelectedItem().toString().equals("Estudiante")){
            c_educativo.setEnabled(true);
            programa.setEnabled(true);
            materia.setEnabled(false);
            facultad.setEnabled(false);
        }else if(Rol.getSelectedItem().toString().equals("Profesor")){
            c_educativo.setEnabled(false);
            programa.setEnabled(false);
            materia.setEnabled(true);
            facultad.setEnabled(true);
        }
        
    }//GEN-LAST:event_RolActionPerformed

    private void jTextFieldC_EducativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldC_EducativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldC_EducativoActionPerformed

    private void jTextFieldMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMateriaActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
        // TODO add your handling code here:
        if(this.usuarios==null){
            this.usuarios=new ArbolAVL();
        }
        
        if(Rol.getSelectedItem().toString().equals("Estudiante")){
            if(jTextNombreUsuario.getText().isEmpty()||jTextNombres.getText().isEmpty()||jTextApellidos.getText().isEmpty()||jPassword.getText().isEmpty()||jTextPaneDescrpicion.getText().isEmpty()){
            jLabelError.setText("Faltan datos por digitar");
        }else{
            Persona estudiante = new Estudiante(jTextNombreUsuario.getText(),(String) genero.getSelectedItem(),jTextNombres.getText(),jTextApellidos.getText(),(String) c_educativo.getSelectedItem(),(String)programa.getSelectedItem(),jPassword.getText(),jTextPaneDescrpicion.getText());
            long inicio=System.nanoTime();
            usuarios.insertarNormal(estudiante, estudiante.idUsuario);
            long finall=System.nanoTime();
        double dif= (double)(finall-inicio)*1.0e-6;
                System.out.println(dif);
            Login volver=new Login(usuarios);
            volver.setVisible(true);
            dispose();
        }
        }else if(Rol.getSelectedItem().toString().equals("Profesor")){
            
            if(jTextNombreUsuario.getText().isEmpty()||jTextNombres.getText().isEmpty()||jTextApellidos.getText().isEmpty()||jPassword.getText().isEmpty()|| jTextPaneDescrpicion.getText().isEmpty()){
            jLabelError.setText("Faltan datos por digitar");
        }else{
            Persona profesor = new Profesor(jTextNombreUsuario.getText(),jTextNombres.getText(),jTextApellidos.getText(),(String) genero.getSelectedItem(),jPassword.getText(),(String) materia.getSelectedItem(),(String) facultad.getSelectedItem(),(String) c_educativo.getSelectedItem(),jTextPaneDescrpicion.getText());
            usuarios.insertarNormal(profesor, profesor.idUsuario);
            Login volver=new Login(usuarios);
            volver.setVisible(true);
            dispose();
        }
        }
        
            
        
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Rol;
    private javax.swing.JComboBox<String> c_educativo;
    private javax.swing.JComboBox<String> facultad;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelAnuncio;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanelFondoRegistro;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextFieldC_Educativo;
    private javax.swing.JTextField jTextFieldFacultad;
    private javax.swing.JTextField jTextFieldMateria;
    private javax.swing.JTextField jTextFieldPrograma;
    private javax.swing.JTextField jTextNombreUsuario;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextPane jTextPaneDescrpicion;
    private javax.swing.JComboBox<String> materia;
    private javax.swing.JComboBox<String> programa;
    // End of variables declaration//GEN-END:variables
}
